myapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'myapp'

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^hostel/$', views.hostel,name='hostel'),
    url(r'^Login/$', views.Login.as_view(),name='Login'),
    url(r'^comment/$', views.comment,name='comment'),
    url(r'^successEdit/$', views.successEdit,name='successEdit'),
    url(r'^Logout/$', views.Logout,name='Logout'),

    url(r'^others/$', views.others,name='others'),
    url(r'^otherscomment/$', views.otherscomment,name='otherscomment'),
    url(r'^successEditothers/$', views.successEditothers,name='successEditothers'),

    url(r'^stud1/$', views.stud1,name='stud1'),
    url(r'^stud2/$', views.stud2,name='stud2'),

]

portal/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls')),
]

myapp/models.py
from __future__ import unicode_literals
from django.db import models

class Student(models.Model):

    rollno = models.CharField(max_length=9,default="15010106")
    name = models.CharField(max_length=70,default="student")
    webmail = models.CharField(max_length=30,default="mail")

    hostel = models.CharField(max_length=50,default="barak")
    hostelVal = models.BooleanField(default=1)
    hostelValC = models.CharField(max_length=700, default="No remarks")

    prof1 = models.BooleanField(default=1)
    prof1C = models.CharField(max_length=700,default="No remarks")

    prof2 = models.BooleanField(default=1)
    prof2C = models.CharField(max_length=700,default="No remarks")

    prof3 = models.BooleanField(default=1)
    prof3C = models.CharField(max_length=700,default="No remarks")

    prof4 = models.BooleanField(default=1)
    prof4C = models.CharField(max_length=700, default="No remarks")

    prof5 = models.BooleanField(default=1)
    prof5C = models.CharField(max_length=700, default="No remarks")

    lab1 = models.BooleanField(default=1)
    lab1C = models.CharField(max_length=700, default="No remarks")

    lab2 = models.BooleanField(default=1)
    lab2C = models.CharField(max_length=700, default="No remarks")

    lab3 = models.BooleanField(default=1)
    lab3C = models.CharField(max_length=700, default="No remarks")

    cc = models.BooleanField(default=1)
    ccC = models.CharField(max_length=700, default="No remarks")

    sa = models.BooleanField(default=1)
    saC = models.CharField(max_length=700, default="No remarks")

    fa = models.BooleanField(default=1)
    faC = models.CharField(max_length=700, default="No remarks")

    workshop = models.BooleanField(default=1)
    workshopC = models.CharField(max_length=700, default="No remarks")

    cenlib = models.BooleanField(default=1)
    cenlibC = models.CharField(max_length=700, default="No remarks")

    cselib = models.BooleanField(default=1)
    cselibC = models.CharField(max_length=700, default="No remarks")


	#string defenition -- used in showAll()
    def __str__(self):
        return self.name

class Proffesor(models.Model):

    name = models.CharField(max_length=70,default="proffesor")
    webmail = models.CharField(max_length=30,default="mailprof")


    hostel = models.CharField(max_length=700,default="NIL")
    hod = models.BooleanField(default=0)

    colName = models.CharField(max_length=700, default="prof")

	#string defenition -- used in showAll()
    def __str__(self):
        return self.name


class Others(models.Model):

    name = models.CharField(max_length=70,default="other")
    webmail = models.CharField(max_length=30,default="mailother")


    colName = models.CharField(max_length=700, default="lab")

	#string defenition -- used in showAll()
    def __str__(self):
        return self.name

myapp/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    class meta:
        model = User
        fields = ['username','password']

myapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.models import User

from django.shortcuts import redirect
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View
from .forms import UserForm
from .models import Student,Proffesor,Others

def index(request):
	if request.user.is_authenticated() and request.user.username != "shivram":
		if request.method == "GET":
			profCheck = Proffesor.objects.filter(webmail=request.user.username)

			if profCheck[0].hod:
				studList = Student.objects.filter(cc=False,sa=False,workshop=False,cselib=False)
				for x in xrange(2,6):
					qry = "prof" + str(x)
					my_filter = {}
					my_filter[qry] = False
					studList = studList.filter(**my_filter)
				profCol = profCheck[0].colName
				return render(request, 'myapp/index.html',{'studList': studList, 'user': profCol, 'hostel': profCheck[0].hostel , 'nameDisplay':profCheck[0].name})

			studList = Student.objects.all()
			profCol = profCheck[0].colName
			return render(request, 'myapp/index.html',{'studList':studList,'user':profCol,'hostel':profCheck[0].hostel, 'nameDisplay':profCheck[0].name})

		else:
			selectStud = request.POST.getlist('selectList')
			for mail in selectStud:
				student = Student.objects.get(webmail=mail)
				userVar = request.user.username
				profCheck = Proffesor.objects.filter(webmail=userVar)
				profCol = profCheck[0].colName

				setattr(student,profCol,False)
				student.save()

			return redirect('myapp:index')

	else:
		return redirect('myapp:Login')

def hostel(request):
	if request.user.is_authenticated() and request.user.username != "shivram":
		if request.method == "GET":

			profCheck = Proffesor.objects.filter(webmail=request.user.username)
			studList = Student.objects.filter(hostel=profCheck[0].hostel)

			return render(request, 'myapp/hostel.html',{'studList':studList,'user':"hostelVal",'hostel':profCheck[0].hostel, 'nameDisplay':profCheck[0].name})

		else:
			selectStud = request.POST.getlist('selectList')
			for mail in selectStud:
				student = Student.objects.get(webmail=mail)
				setattr(student,"hostelVal",False)
				student.save()

			return redirect('myapp:hostel')

	else:
		return redirect('myapp:Login')

def comment(request):
	if request.user.is_authenticated() and request.user.username != "shivram":
		if request.method == "GET":
			profCheck = Proffesor.objects.filter(webmail=request.user.username)
			return render(request,'myapp/choice.html',{'hostel':profCheck[0].hostel})
		else:
			if request.POST['action'] == "ch":
				if request.POST['choose'] == "dept":
					studList = Student.objects.all()
					profCheck = Proffesor.objects.filter(webmail=request.user.username)
					profCol = profCheck[0].colName
					return render(request, 'myapp/comment.html', {'studList': studList,'user':profCol,'hostel':profCheck[0].hostel})
				else:
					profCheck = Proffesor.objects.filter(webmail=request.user.username)
					studList = Student.objects.filter(hostel=profCheck[0].hostel)
					profCol = "hostelVal"
					return render(request, 'myapp/comment.html',{'studList': studList, 'user': profCol, 'hostel': profCheck[0].hostel})

			else:
				pkFind = request.POST['studentComment']
				student = Student.objects.get(pk=pkFind)
				profCheck = Proffesor.objects.filter(webmail=request.user.username)
				profCol = request.POST['column']
				return render(request, 'myapp/edit.html', {'student': student, 'user': profCol,'hostel':profCheck[0].hostel})
	else:
		return redirect('myapp:Login')

def successEdit(request):
	if request.method == "GET":
		return redirect('myapp:index')
	else:
		textEntered=request.POST['newComment']
		pkFind = request.POST['pkStud']
		student = Student.objects.get(pk=pkFind)

		profCol = request.POST['column']
		profCol = profCol + "C"

		setattr(student,profCol,textEntered)
		student.save()

		if profCol == "hostelValC":
			return redirect('myapp:hostel')

		return redirect('myapp:index')


class Login(View):
	form_class = UserForm
	template_name = 'myapp/login.html'

	def  get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def  post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			checkUser = authenticate(username=username,password=password)

			if checkUser is not None:
				if checkUser.is_active:
					login(request,checkUser)
					if checkUser.username == "shivram":
						return redirect('/admin')
					else:
						profCheck = Proffesor.objects.filter(webmail=username)
						if profCheck.count():
							return redirect('myapp:index')
						else:
							otherCheck = Others.objects.filter(webmail=username)
							if otherCheck.count():
								return redirect('myapp:others')
							else:
								return redirect('myapp:stud1')
			else:
				return render(request, self.template_name, {'form': form})
		else:
			return render(request, self.template_name, {'form': form})



def Logout(request):
	if request.user.is_authenticated():
		logout(request)
	return redirect('myapp:Login')


def others(request):
	if request.user.is_authenticated() and request.user.username != "shivram": #CHANGE
		#return HttpResponse('<p>u r logged in</p>')
		if request.method == "GET":

			otherCheck = Others.objects.filter(webmail=request.user.username)

			if otherCheck[0].webmail == "fa":
				studList = Student.objects.filter(prof1=False)
				otherCol = otherCheck[0].colName
				return render(request, 'myapp/others.html', {'studList': studList, 'user': otherCol, 'nameDisplay':otherCheck[0].name})

			studList = Student.objects.all()
			otherCol = otherCheck[0].colName
			return render(request, 'myapp/others.html',{'studList':studList,'user':otherCol, 'nameDisplay':otherCheck[0].name})

		else:
			selectStud = request.POST.getlist('selectList')
			for mail in selectStud:
				student = Student.objects.get(webmail=mail)
				userVar = request.user.username
				otherCheck = Others.objects.filter(webmail=userVar)
				otherCol = otherCheck[0].colName

				setattr(student,otherCol,False)
				student.save()

			return redirect('myapp:others')

	else:
		return redirect('myapp:Login')



def otherscomment(request):
	if request.user.is_authenticated() and request.user.username != "shivram": #CHANGE
		if request.method == "GET":
			studList = Student.objects.all()
			otherCheck = Others.objects.filter(webmail=request.user.username)
			otherCol = otherCheck[0].colName
			return render(request, 'myapp/otherscomment.html',{'studList': studList, 'user': otherCol})
		else:
			pkFind = request.POST['studentComment']
			student = Student.objects.get(pk=pkFind)
			otherCheck = Others.objects.filter(webmail=request.user.username)
			otherCol = otherCheck[0].colName
			return render(request, 'myapp/othersedit.html', {'student': student, 'user': otherCol})
	else:
		return redirect('myapp:Login')

def successEditothers(request):
	if request.method == "GET":
		return redirect('myapp:others')
	else:
		textEntered=request.POST['newComment']
		pkFind = request.POST['pkStud']
		student = Student.objects.get(pk=pkFind)

		otherCol = request.POST['column']
		otherCol = otherCol + "C"

		setattr(student,otherCol,textEntered)
		student.save()

		return redirect('myapp:others')





def stud1(request):
	if request.user.is_authenticated():
		all_albums=Student.objects.all()
		context1={'all_albums':all_albums,'webmail':request.user.username}
		return render(request,"myapp/inde.html",context1)
	else:
		return redirect('myapp:Login')


def stud2(request):
	if request.user.is_authenticated():
		all_albums=Student.objects.all()
		context1={'all_albums':all_albums,'webmail':request.user.username}
		return render(request,"myapp/inde1.html",context1)
	else:
		return redirect('myapp:Login')

myapp/templates/myapp/choice.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


{% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/reset.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
	<script src="{% static 'myapp/modernizr.js' %}"></script> <!-- Modernizr -->

<title>Choose</title>

    <header>
        <nav class="cd-stretchy-nav">
            <a class="cd-nav-trigger" href="#0">

                <span aria-hidden="true"></span>
            </a>

            <ul>
                <li><a href="{% url 'myapp:index' %}" class="active"><span>Department</span></a></li>
                {% ifnotequal hostel "NIL"%}
                <li><a href="{% url 'myapp:hostel' %}"><span>{{ hostel }} Hostel</span></a></li>
                {% endifnotequal %}
                <li><a href="{% url 'myapp:comment' %}"><span>Edit Comment</span></a></li>
                <li><a href="{% url 'myapp:Logout' %}"><span>Logout</span></a></li>
            </ul>

            <span aria-hidden="true" class="stretchy-nav-bg"></span>
        </nav>
    </header>



<main class="cd-main-content">
	<!-- main content here -->

    <div class="studentList">
        <h2>Hostel or Dept?</h2><br><br>

        <form action="{% url 'myapp:comment' %}" method="post" class="list" >
            {% csrf_token %}

            <div class="select-style">
              <select name="choose">
                <option value="dept">Department</option>
                {% ifequal hostel "NIL" %}
                    <option disabled >Hostel(NA)</option>
                {% endifequal %}
                {% ifnotequal hostel "NIL" %}
                    <option value="host" >Hostel {{ hostel }}</option>
                {% endifnotequal %}
              </select>
            </div>

            <br><br>
                <div class="col-sm-offset-2 col-sm-1">
                    <button type="submit" name="action" value="ch" class="btn btn-success">Edit</button>
                </div>
        </form>
    </div>


</main>

<script src="{% static 'myapp/main.js' %}"></script>

myapp/templates/myapp/comment.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


{% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/reset.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
	<script src="{% static 'myapp/modernizr.js' %}"></script> <!-- Modernizr -->

<title>Comment</title>

    <header>
        <nav class="cd-stretchy-nav">
            <a class="cd-nav-trigger" href="#0">

                <span aria-hidden="true"></span>
            </a>

            <ul>
                <li><a href="{% url 'myapp:index' %}" class="active"><span>Department</span></a></li>
                {% ifnotequal hostel "NIL"%}
                <li><a href="{% url 'myapp:hostel' %}"><span>{{ hostel }} Hostel</span></a></li>
                {% endifnotequal %}
                <li><a href="{% url 'myapp:comment' %}"><span>Edit Comment</span></a></li>
                <li><a href="{% url 'myapp:Logout' %}"><span>Logout</span></a></li>
            </ul>

            <span aria-hidden="true" class="stretchy-nav-bg"></span>
        </nav>
    </header>


<main class="cd-main-content">
	<!-- main content here -->

    <div class="studentList">
        <h2>Select from the list</h2><br><br>

        <form action="" method="post" class="list" >
            {% csrf_token %}

            <div class="select-style">
              <select name="studentComment">
                {% for student  in studList %}
                    <option value="{{ student.pk }}">{{ student.name }} ( {{ student.rollno }} )</option>
                {% endfor %}
              </select>
            </div>
        <input type="hidden" name="column" value="{{ user }}">
            <br><br>
                <div class="col-sm-offset-2 col-sm-1">
                    <button type="submit" name="action" value="cm" class="btn btn-success">Edit</button>
                </div>
        </form>
    </div>


</main>

<script src="{% static 'myapp/main.js' %}"></script>

myapp/templates/myapp/edit.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


{% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/reset.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
	<script src="{% static 'myapp/modernizr.js' %}"></script> <!-- Modernizr -->

<title>Edit comment</title>


    <header>
        <nav class="cd-stretchy-nav">
            <a class="cd-nav-trigger" href="#0">

                <span aria-hidden="true"></span>
            </a>

            <ul>
                <li><a href="{% url 'myapp:index' %}" class="active"><span>Department</span></a></li>
                {% ifnotequal hostel "NIL"%}
                <li><a href="{% url 'myapp:hostel' %}"><span>{{ hostel }} Hostel</span></a></li>
                {% endifnotequal %}
                <li><a href="{% url 'myapp:comment' %}"><span>Edit Comment</span></a></li>
                <li><a href="{% url 'myapp:Logout' %}"><span>Logout</span></a></li>

            </ul>

            <span aria-hidden="true" class="stretchy-nav-bg"></span>
        </nav>
    </header>



<main class="cd-main-content">
	<!-- main content here -->

    <div class="studentList">

        <form id="my_form" action="{% url 'myapp:successEdit' %}" method="post" class="list" >
            {% csrf_token %}

            <h4>Student Details:</h4>
            <h4>{{ student.name }}</h4>
            <h4>{{ student.rollno }}</h4><br><br>

            <label for="text1"> Edit your comment here</label>
           <br><br>

             {% load getattribute %}
            {% load addstr %}
            <input name="pkStud" type="hidden" value="{{ student.id }}">
            <input name="column" type="hidden" value="{{ user }}">
            {% with user|addstr:"C" as field %}
                <textarea class="longInput" form="my_form" name="newComment" id="text1" cols="35" rows="7"  style="font-size:12pt;" >{{ student|getattribute:field }}
              </textarea>
            {% endwith %}

            <br><br>
                <div class="col-sm-offset-6 col-sm-1">
                    <button type="submit" class="btn btn-success">Edit comment</button>
                </div>
        </form>
    </div>


</main>

<script src="{% static 'myapp/main.js' %}"></script>

myapp/templates/myapp/hostel.html
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">


{% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/reset.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
	<script src="{% static 'myapp/modernizr.js' %}"></script> <!-- Modernizr -->

<title>Hostel List</title>

    <header>
        <nav class="cd-stretchy-nav">
            <a class="cd-nav-trigger" href="#0">

                <span aria-hidden="true"></span>
            </a>

            <ul>
                <li><a href="{% url 'myapp:index' %}" class="active"><span>Department</span></a></li>
                {% ifnotequal hostel "NIL"%}
                <li><a href="{% url 'myapp:hostel' %}"><span>{{ hostel }} Hostel</span></a></li>
                {% endifnotequal %}
                <li><a href="{% url 'myapp:comment' %}"><span>Edit Comment</span></a></li>
                <li><a href="{% url 'myapp:Logout' %}"><span>Logout</span></a></li>
            </ul>

            <span aria-hidden="true" class="stretchy-nav-bg"></span>
        </nav>
    </header>




<main class="cd-main-content">
	<!-- main content here -->

    <div class="studentList">
        <h2>Welcome {{ nameDisplay }}</h2><br><br>
        <h3>Hostel {{ hostel }} Students</h3>

        <form action="" method="post" class="list" >
            {% csrf_token %}



            <table id="acrylic">
            <thead>
            <tr>
                <th>Select</th>
                <th>Student</th>
                <th>Comments</th>
            </tr>
            </thead>
            <tbody>
            {% for student  in studList %}
                {% load getattribute %}
                {% load addstr %}
                {% if student|getattribute:user %}
                    <tr>
                        <td align="center" style="vertical-align:middle;"><input type="checkbox" value="{{ student.webmail }}" name="selectList"></td>
                        <td align="center" style="vertical-align:middle;">{{ student.name }}</td>
                        {% with user|addstr:"C" as field %}
                        <td>
                            <textarea readonly class="longInput" cols="35" rows="7"  style="font-size:12pt;" >{{ student|getattribute:field }}
                        </textarea>
                        </td>
                        {% endwith %}
                    </tr>
                {% endif %}
            {% endfor %}

            </tbody>
            </table>
            <input type="checkbox" name="temporary" onClick="toggle(this)" /> Toggle All<br/>
            <br><br>
                <div class="col-sm-offset-2 col-sm-8">
                    <button type="submit" class="btn btn-success">Clear Dues</button>
                </div>
        </form>
        <br><br><br><br><br><br><br><br><br><br>
        Copyrights reserved
    </div>

</main>

<script src="{% static 'myapp/main.js' %}"></script>


<script language="JavaScript">
function toggle(source) {
  checkboxes = document.getElementsByName('selectList');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
}
</script>

myapp/templates/myapp/inde.html
<!DOCTYPE html>
<html>
<head>
	<center>
		<h1>DUE LIST</h1>
	</center>
</head>

{% load staticfiles %}
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/reset.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
	<script src="{% static 'myapp/modernizr.js' %}"></script> <!-- Modernizr -->

<title>Dept</title>



<body>


<style type="text/css">

	body {
		background-image: url("../../static/myapp/images/url.jpg");
		background-repeat: no-repeat;
		background-position: top left;
		background-attachment: fixed;
		/* Demo style */
		text-shadow: 0 1px 0 #fff;
}

strong {
	font-weight: bold;
}

em {
	font-style: italic;
}

table {
	background: #f5f5f5;
	border-collapse: separate;
	box-shadow: inset 0 1px 0 #fff;
	font-size: 12px;
	line-height: 24px;
	margin: 30px auto;
	text-align: left;
	width: 800px;
}

th {
	background: url(http://jackrugile.com/images/misc/noise-diagonal.png), linear-gradient(#777, #444);
	border-left: 1px solid #555;
	border-right: 1px solid #777;
	border-top: 1px solid #555;
	border-bottom: 1px solid #333;
	box-shadow: inset 0 1px 0 #999;
	color: #fff;
  font-weight: bold;
	padding: 10px 15px;
	position: relative;
	text-shadow: 0 1px 0 #000;
}

th:after {
	background: linear-gradient(rgba(255,255,255,0), rgba(255,255,255,.08));
	content: '';
	display: block;
	height: 25%;
	left: 0;
	margin: 1px 0 0 0;
	position: absolute;
	top: 25%;
	width: 100%;
}

th:first-child {
	border-left: 1px solid #777;
	box-shadow: inset 1px 1px 0 #999;
}

th:last-child {
	box-shadow: inset -1px 1px 0 #999;
}

td {
	border-right: 1px solid #fff;
	border-left: 1px solid #e8e8e8;
	border-top: 1px solid #fff;
	border-bottom: 1px solid #e8e8e8;
	padding: 10px 15px;
	position: relative;
	transition: all 300ms;
}

td:first-child {
	box-shadow: inset 1px 0 0 #fff;
}

td:last-child {
	border-right: 1px solid #e8e8e8;
	box-shadow: inset -1px 0 0 #fff;
}

tr {
	background: url(http://jackrugile.com/images/misc/noise-diagonal.png);
}

tr:nth-child(odd) td {
	background: #f1f1f1 url(http://jackrugile.com/images/misc/noise-diagonal.png);
}

tr:last-of-type td {
	box-shadow: inset 0 -1px 0 #fff;
}

tr:last-of-type td:first-child {
	box-shadow: inset 1px -1px 0 #fff;
}

tr:last-of-type td:last-child {
	box-shadow: inset -1px -1px 0 #fff;
}

tbody:hover td {
	color: transparent;
	text-shadow: 0 0 3px #aaa;
}

tbody:hover tr:hover td {
	color: #444;
	text-shadow: 0 1px 0 #fff;
}
</style>
<center><table>
	<tr>
	<th>Webmail ID</th>
	<th>Professor Name</th>
	<th>Commments</th>
	</tr>
		{% for album in all_albums %}

                {% if album.webmail == webmail %}
                    {% with 'prof1 prof2 prof3 prof4 prof5' as list %}
                    {% for item in list.split %}
                    <tr>
                        {% load getattribute %}

                        {% if album|getattribute:item %}
                        {% load addstr %}
                        {% load retprof %}
                        {% with item|retprof as prof%}
                            {% load retprof4 %}
                         <td>{{ item|retprof4 }}</td>
                        <td>{{ prof }}</td>
                        {% endwith %}
                        {% with item|addstr:"C" as comment %}
                        <td>{{ album|getattribute:comment }}</td>
                        {% endwith %}
                        {% endif %}
                    </tr>

                    {% endfor %}
                    {% endwith %}
                {% endif %}
        {% endfor %}
</table>
</center>

<header>
        <nav class="cd-stretchy-nav">
            <a class="cd-nav-trigger" href="#0">

                <span aria-hidden="true"></span>
            </a>

            <ul>
                <li><a href="{% url 'myapp:stud1' %}" class="active"><span>Department</span></a></li>

                <li><a href="{% url 'myapp:stud2' %}"><span>Miscellaneous</span></a></li>
                <li><a href="{% url 'myapp:Logout' %}"><span>Logout</span></a></li>
            </ul>

            <span aria-hidden="true" class="stretchy-nav-bg"></span>
        </nav>
    </header>

</body>
</html>
<script src="{% static 'myapp/main.js' %}"></script>